# Generated by Django 5.0.1 on 2025-12-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_replace_is_premium_with_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "html_template",
                    models.TextField(
                        help_text="Template HTML avec variables {{ variable_name }}"
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True, help_text="Styles CSS pour le template"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Template par défaut pour les nouvelles factures",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template de facture",
                "verbose_name_plural": "Templates de factures",
                "db_table": "invoice_templates",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
