# Generated by Django 5.0.1 on 2025-12-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_invoicetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicetemplate",
            name="js_script",
            field=models.TextField(
                blank=True, help_text="Code JavaScript optionnel pour le template"
            ),
        ),
    ]
