# Generated by Django 5.0.1 on 2025-12-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0007_alter_tenant_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nom du projet/site", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug unique pour le projet", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description du projet"),
                ),
                (
                    "is_system_project",
                    models.BooleanField(
                        default=False,
                        help_text="Projet système (pages publiques VTCBuilder)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("archived", "Archivé"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Domaine personnalisé (ex: mon-site.com)",
                        max_length=255,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant propriétaire du projet (null = projet système/public)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_slug",
                    models.CharField(
                        help_text="Slug de la page (pour pages publiques) ou ID (pour pages tenant)",
                        max_length=255,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("public", "Page Publique"),
                            ("tenant", "Page Tenant"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page de Projet",
                "verbose_name_plural": "Pages de Projet",
                "db_table": "project_pages",
                "ordering": ["order", "-created_at"],
                "unique_together": {("project", "page_slug", "page_type")},
            },
        ),
    ]
