# Generated by Django 5.0.1 on 2025-12-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Page active dans le projet (affichée sur le site)",
            ),
        ),
    ]
