# Generated by Django 5.0.1 on 2025-12-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_unique_page_per_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectpage",
            unique_together={("project", "page_slug", "page_type")},
        ),
    ]
