# Generated by Django 5.0.1 on 2025-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="featureusage",
            new_name="feature_usa_tenant__c0cb42_idx",
            old_name="feature_usage_tenant_usage_idx",
        ),
        migrations.RenameIndex(
            model_name="featureusage",
            new_name="feature_usa_feature_e2afda_idx",
            old_name="feature_usage_feature_usage_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_created_b3dd6c_idx",
            old_name="user_action_created_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_action__d85d5d_idx",
            old_name="user_action_type_created_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_user_id_7cac18_idx",
            old_name="user_action_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_tenant__188879_idx",
            old_name="user_action_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="useraction",
            new_name="user_action_resourc_41bc5b_idx",
            old_name="user_action_resource_idx",
        ),
        migrations.AlterField(
            model_name="useraction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page View"),
                    ("page_create", "Page Created"),
                    ("page_edit", "Page Edited"),
                    ("page_delete", "Page Deleted"),
                    ("block_add", "Block Added"),
                    ("block_edit", "Block Edited"),
                    ("block_delete", "Block Deleted"),
                    ("block_click", "Block Clicked"),
                    ("service_create", "Service Created"),
                    ("service_edit", "Service Edited"),
                    ("service_delete", "Service Deleted"),
                    ("booking_create", "Booking Created"),
                    ("booking_edit", "Booking Edited"),
                    ("booking_delete", "Booking Deleted"),
                    ("template_use", "Template Used"),
                    ("button_click", "Button Clicked"),
                    ("link_click", "Link Clicked"),
                    ("form_submit", "Form Submitted"),
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("register", "User Registration"),
                    ("subscription_create", "Subscription Created"),
                    ("subscription_update", "Subscription Updated"),
                    ("payment_success", "Payment Succeeded"),
                    ("payment_failed", "Payment Failed"),
                    ("feature_use", "Feature Used"),
                    ("project_create", "Project Created"),
                    ("project_edit", "Project Edited"),
                    ("project_delete", "Project Deleted"),
                    ("cta_click", "CTA Clicked"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
