# Generated by Django 5.0.1 on 2025-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_replace_is_premium_with_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("business", "Business"),
                    ("enterprise", "Entreprise"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
    ]
