# Generated by Django 5.0.1 on 2025-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0003_remove_requires_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktype",
            name="render_template",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Template de rendu React en JSON (structure, props, children)",
            ),
        ),
    ]
