# Generated by Django 5.0.1 on 2025-12-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0004_add_render_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallToAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom du CTA (ex: Bouton Principal, Lien Contact)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Libellé affiché", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description du CTA", null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("button", "Bouton"),
                            ("link", "Lien"),
                            ("banner", "Bannière"),
                            ("popup", "Popup"),
                            ("inline", "Inline"),
                            ("sticky", "Fixe"),
                            ("floating", "Flottant"),
                        ],
                        default="button",
                        help_text="Type de CTA",
                        max_length=50,
                    ),
                ),
                (
                    "default_text",
                    models.CharField(
                        default="Cliquez ici",
                        help_text="Texte par défaut",
                        max_length=255,
                    ),
                ),
                (
                    "default_url",
                    models.CharField(
                        default="#", help_text="URL par défaut", max_length=500
                    ),
                ),
                (
                    "styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styles CSS (ex: {background: '#3B82F6', color: '#FFFFFF', borderRadius: '8px'})",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration avancée (target, rel, onclick, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Activer/désactiver ce CTA"
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=True, help_text="CTA disponible pour tous les blocs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Call-to-Action",
                "verbose_name_plural": "Call-to-Actions",
                "db_table": "call_to_actions",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="blocktype",
            name="call_to_action",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration des call-to-action (déprécié - utiliser call_to_actions)",
            ),
        ),
        migrations.AddField(
            model_name="blocktype",
            name="call_to_actions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Call-to-actions disponibles pour ce bloc",
                related_name="blocks",
                to="blocks.calltoaction",
            ),
        ),
    ]
