# Generated by Django 5.0.1 on 2025-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0005_calltoaction_alter_blocktype_call_to_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktype",
            name="is_admin_only",
            field=models.BooleanField(
                default=False,
                help_text="Réservé aux administrateurs uniquement (non visible pour les utilisateurs normaux)",
            ),
        ),
    ]
