# Generated by Django 5.0.1 on 2025-12-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_add_project_to_media"),
        ("media", "20251128_add_template_fields"),
    ]

    operations = []
