# Generated by Django 5.0.1 on 2025-12-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "20251129_merge_20251205_1424"),
        ("media", "20251210_fix_template_slug_index"),
    ]

    operations = []
