# Generated by Django 5.0.1 on 2025-12-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0006_add_public_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="maintenance_mode_type",
            field=models.CharField(
                choices=[
                    ("public_only", "Site public seulement (VTCBuilder)"),
                    ("platform_except_admin", "Plateforme entière sauf admin"),
                ],
                default="public_only",
                help_text="Type de mode maintenance",
                max_length=25,
            ),
        ),
    ]
