# Generated by Django 5.0.1 on 2025-12-05 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0007_alter_tenant_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ip_whitelist", "IP Whitelist"),
                            ("ip_blacklist", "IP Blacklist"),
                            ("country_whitelist", "Country Whitelist"),
                            ("country_blacklist", "Country Blacklist"),
                            ("asn_whitelist", "ASN Whitelist"),
                            ("asn_blacklist", "ASN Blacklist"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="IPs, countries, ASNs, etc."
                    ),
                ),
                ("priority", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Règle Firewall",
                "verbose_name_plural": "Règles Firewall",
                "db_table": "firewall_rules",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waf_enabled",
                    models.BooleanField(default=True, help_text="Activer le WAF"),
                ),
                (
                    "waf_mode",
                    models.CharField(
                        choices=[
                            ("blocking", "Blocking Mode"),
                            ("monitoring", "Monitoring Mode"),
                            ("learning", "Learning Mode"),
                        ],
                        default="blocking",
                        max_length=20,
                    ),
                ),
                ("rate_limit_enabled", models.BooleanField(default=True)),
                ("rate_limit_requests_per_minute", models.IntegerField(default=60)),
                ("rate_limit_requests_per_hour", models.IntegerField(default=1000)),
                ("ip_reputation_enabled", models.BooleanField(default=True)),
                ("block_known_bad_ips", models.BooleanField(default=True)),
                (
                    "log_all_requests",
                    models.BooleanField(
                        default=False,
                        help_text="Logger toutes les requêtes (peut être volumineux)",
                    ),
                ),
                (
                    "log_retention_days",
                    models.IntegerField(
                        default=30, help_text="Nombre de jours de rétention des logs"
                    ),
                ),
                ("alert_on_critical", models.BooleanField(default=True)),
                ("alert_on_high", models.BooleanField(default=True)),
                ("alert_on_medium", models.BooleanField(default=False)),
                (
                    "alert_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email pour les alertes de sécurité",
                        max_length=254,
                    ),
                ),
                (
                    "auto_block_after_attempts",
                    models.IntegerField(
                        default=5,
                        help_text="Bloquer automatiquement après N tentatives",
                    ),
                ),
                (
                    "auto_block_duration_hours",
                    models.IntegerField(
                        default=24, help_text="Durée du blocage automatique (heures)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de Sécurité",
                "verbose_name_plural": "Paramètres de Sécurité",
                "db_table": "security_settings",
            },
        ),
        migrations.CreateModel(
            name="WAFRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Nom de la règle", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description de la règle"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ip_whitelist", "IP Whitelist"),
                            ("ip_blacklist", "IP Blacklist"),
                            ("rate_limit", "Rate Limiting"),
                            ("sql_injection", "SQL Injection Protection"),
                            ("xss", "XSS Protection"),
                            ("path_traversal", "Path Traversal Protection"),
                            ("file_upload", "File Upload Protection"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("testing", "Testing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration de la règle (IPs, patterns, etc.)",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Priorité de la règle (plus bas = plus prioritaire)",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("block", "Block"),
                            ("challenge", "Challenge (CAPTCHA)"),
                            ("log", "Log Only"),
                        ],
                        default="block",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waf_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle WAF",
                "verbose_name_plural": "Règles WAF",
                "db_table": "waf_rules",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WAFLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(max_length=10)),
                ("request_path", models.TextField()),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body", models.TextField(blank=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("blocked", "Blocked"),
                            ("challenged", "Challenged"),
                            ("logged", "Logged"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Raison du blocage/action"),
                ),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waf_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "matched_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="security.wafrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log WAF",
                "verbose_name_plural": "Logs WAF",
                "db_table": "waf_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("attack_detected", "Attack Detected"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("ip_blocked", "IP Blocked"),
                            ("rule_triggered", "Rule Triggered"),
                            ("system_anomaly", "System Anomaly"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("notified", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_alerts_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="security.waflog",
                    ),
                ),
                (
                    "related_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="security.wafrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte de Sécurité",
                "verbose_name_plural": "Alertes de Sécurité",
                "db_table": "security_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="waflog",
            index=models.Index(
                fields=["-timestamp", "ip_address"], name="waf_logs_timesta_ab56eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waflog",
            index=models.Index(
                fields=["-timestamp", "severity"], name="waf_logs_timesta_18491c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waflog",
            index=models.Index(
                fields=["-timestamp", "action"], name="waf_logs_timesta_d630c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityalert",
            index=models.Index(
                fields=["-created_at", "status"], name="security_al_created_043c8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityalert",
            index=models.Index(
                fields=["-created_at", "severity"],
                name="security_al_created_e51711_idx",
            ),
        ),
    ]
